### PR TITLE
Expand admonition when user tries to modify their own karma.

### PR DESCRIPTION
**Pull request by aslicerh**

### CODE REVIEW

**Comment by relrod** [comment]
I'm -1 for two reasons:

* One line is annoying enough (I'd honestly prefer no output at all when nothing happens), three lines is crazy!
* The bot's nick shouldn't be hardcoded anywhere in the plugin because it could theoretically change.

**Comment by aslicerh** [comment]
@relrod 
I can understand the annoyance with the 3 lines. I just figured it would be pretty rare that someone would try to deduct karma from themselves, so the joke might be ok.

Regarding hard coding the name, I can also agree with that, but it is done in other places in the plugin ([localtime](https://github.com/aslicerh/supybot-fedora/blob/0f5444a372ef7f10c896e061f92db302921e3f5c/plugin.py#L555)) so I figured it was the accepted procedure. I didn't notice anywhere else that the bots name was used, so what is the suggested way to know the bots name?

**Comment by relrod** [comment]
I think `conf.supybot.nick` would work (at least it does in a quick test), although it doesn't seem to update if someone changes the nick while the bot is running.

And yeah, I don't think `localtime` should hardcode the nick either...

**Comment by ryanlerch** [comment]
closing this off due to inactivity. please reopen if still desired

**Pull request closed without merging**
